-   id: coverage-badge
    name: generate the coverage badge
    entry: coverage-badge
    language: python
    pass_filenames: false
    always_run: true
    stages: [commit, push, manual]
-   id: coverage-html-report
    name: generate the coverage html report
    entry: coverage-html-report
    language: python
    pass_filenames: false
    always_run: true
    stages: [commit, push, manual]

